DROP TABLE IF EXISTS TB_HEROIS;
CREATE TABLE TB_HEROIS (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NOME TEXT NOT NULL,
    PODER TEXT NOT NULL
)
-- create
INSERT INTO TB_HEROIS(NOME,PODER)
VALUES
    ('superman', 'over power'),


SELECT * FROM TB_HEROIS;
SELECT * FROM TB_HEROIS WHERE NOME='Batman';
SELECT NOME FROM TB_HEROIS WHERE NOME='Batman';

--update

UPDATE TB_HEROIS 
SET NOME='HOMEM DE FERRO', PODER='DINHEIRO' 
WHERE ID=2

--delete

DELETE FROM TB_HEROIS WHERE ID=1;
SELECT * FROM TB_HEROIS;
